### ISSUE TITLE
@SubCommand args.length Abfragen

### ISSUE THREAD

**Issue by Schmazda** [JohnnyJayJay/discord-api-command#22]
Ich bin gerade dabei von zekros Command System(JDA Tutorial) auf deine API zu wechseln und merke gerade, dass mir in den Abstract Commands eine SubCommand Argument Length Abfrage fehlt.

Wäre das machbar?

LG

**Comment by lus** [comment]
Kannst du nicht `moreArgs` so setzen, dass es passt und dann in der Methode die length überprüfen? War jetzt so 'ne spontane Idee.

**Comment by Schmazda** [comment]
Hab ich im Endeffekt auch so gemacht, aber wirklich schön sieht das nicht aus

**Comment by JohnnyJayJay** [comment]
I think this issue is resolved. Please keep the issues English so everybody can understand and apply the solutions presented here.
