### ISSUE TITLE
Multiple pre-defined args

### ISSUE THREAD

**Issue by zThana** [JohnnyJayJay/discord-api-command#24]
Hey,

Hoping this will be looked at, I'm trying to make it so you can use multiple args using the same command. I don't know how to and I can't figure out how to accomplish this.

How would I make .example <option1 | option2> <choice1 | choice2>
So I can use .example option1 choice2 and .example option2 choice1 etc with different outcomes.

Thanks in advance,
Thana

**Comment by JohnnyJayJay** [comment]
Yes, you can do that. You have two possibilities:
Either you check the arguments in your command method like here:
```java
public class ExampleCommand implements ICommand {
	@Override
	public void onCommand(CommandEvent event, Member member, TextChannel channel, String[] args) {
		if (args.length != 2)
			return;
		
		String option = args[0];
		String choice = args[1];
		// validate these and react
	}
}
```
Registering this via `CommandSettings.put(new ExampleCommand(), "example")`, you could execute the command with any arguments. However, in this case you still have to validate the arguments yourself. To make the framework responsible for this, you may use `AbstractCommand`:
```java
public class ExampleCommand extends AbstractCommand {
	@SubCommand(args = {"option1|option2", "choice1|choice2"}) // regex
	public void exampleCommand(CommandEvent event, Member member, TextChannel channel, String[] args) {
		// You can use the arguments here as they were already validated
	}
}
```
