### ISSUE TITLE
Base method

### ISSUE THREAD

**Issue by zThana** [JohnnyJayJay/discord-api-command#25]
Hey,

Is there a base method (except for the message event) I could use which is being ran before all other commands?

I've been going after it for a while but it doesn't seem like there's something like that.

Kind regards

EDIT: Should've looked closer. CommandEvent is what I'm looking for, thank you

**Comment by zThana** [comment]
Reopening considering I can't figure out how to listen to this specific event. I tried extending to ListenerAdapter but that didn't seem to pick up anything.

**Comment by zThana** [comment]
I ended up modifying the code for my specific purposes after my friend and I realized the API wasn't capable of doing so. Feel free to correct me, would like to see what you think

**Comment by JohnnyJayJay** [comment]
You are right. There's no way of intercepting/listening for `CommandEvent` and there won't be in the future, as this library is not being actively updated/maintained anymore.
You're free to modify it so that it meets your needs, of course.

**Comment by zThana** [comment]
Got it, thank you.
